SRC = src/ft_add.c src/ft_atoi.c src/ft_divide.c src/ft_modulo.c src/ft_minus.c src/ft_multiply.c src/ft_putnbr.c src/main.c
OBJ = ${SRC:.c=.o}


all :
	cc -Wall -Wextra -Werror ${SRC} -o do-op
clean :
	rm -rf ${OBJ}
fclean :
	rm -rf do-op